kind: Deployment
apiVersion: apps/v1
# ----------------------
metadata:
    name: {{ .Release.Name }}-order
spec:
    replicas: 1
    selector:
        matchLabels:
            app: order
    template:
        metadata:
            labels:
                app: order
        spec:
            containers:
                - name: order
                  image: mppise/order:1.1.0
                  ports:
                      - containerPort: 8080

---
kind: Service
apiVersion: v1
# -------------------
metadata:
    name: {{ .Release.Name }}-order-svc
spec:
    selector:
        app: order
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: {{ .Release.Name }}-online-store-order-apis
  labels:
    app.kubernetes.io/name: online-store-order-apis
spec:
  service:
    name: {{ .Release.Name }}-order-svc
    port: 8080
  host: ordersapi.f976b46.kyma.ondemand.com
  rules:
    - path: (/|$)(.*)
      methods:
        - GET
        - POST
        - DELETE
        - PUT
        - OPTIONS
      accessStrategies:
        - handler: allow
  gateway: kyma-gateway.kyma-system.svc.cluster.local
