kind: Secret
apiVersion: v1
# -----------------
type: Opaque
metadata:
  name: github-secret
data:
  username: bXBwaXNlQGdtYWlsLmNvbQ==
  password: bnVxaHVoLTNaeXZreS1rZWh3aWM=

---
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
# -----------------
metadata:
  name: ping
  labels:
    app.kubernetes.io/name: ping
spec:
  runtime: "nodejs14"
  source:
    gitRepository:
      url: "https://github.com/mppise/full-stack-microservices.git"
      baseDir: "/1.middleware/ping/"
      reference: "main"
      auth:
        type: "basic"
        secretName: "github-secret"
  env:
    - name: CREDSTORE_URL
      valueFrom:
        secretKeyRef:
          name: credstore
          key: url
    - name: CREDSTORE_USERNAME
      valueFrom:
        secretKeyRef:
          name: credstore
          key: username
    - name: CREDSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: credstore
          key: password
    - name: CREDSTORE_ENCRYPTION
      valueFrom:
        secretKeyRef:
          name: credstore
          key: encryption

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
# -----------------
metadata:
  name: ping
  labels:
    app.kubernetes.io/name: ping
spec:
  service:
    name: ping
    port: 80
  host: ping.c-32f130e.kyma.ondemand.com
  rules:
    - path: /.*
      methods:
        - GET
        - POST
        - DELETE
        - PUT
        - OPTIONS
      accessStrategies:
        - handler: allow
  gateway: kyma-gateway.kyma-system.svc.cluster.local

---
apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
# -----------------
metadata:
  name: ping-sub
  namespace: default
spec:
  sink: 'http://ping.default.svc.cluster.local'
  filter:
    filters:
      - eventSource:
          property: source
          type: exact
          value: ''
        eventType:
          property: type
          type: exact
          value: sap.kyma.custom.ping.key.created.v1
