
---
apiVersion: v1
kind: Config
current-context: shoot--kyma--c-93b5b3a
clusters:
- name: shoot--kyma--c-93b5b3a
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWM2Z0F3SUJBZ0lRYURSdkpaM29xM1dhMVFEV012YjJ0VEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TXpBeE1Ea3hOalEzTVRoYUZ3MHpNekF4TURreE5qUTNNVGhhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwR1diClc3OHRncHBxTjdHZC9NMUFFWFd4cUt4d3QwM3VrSFd2L3VtSHRMYmx3QlUranJrVW1Yd3dsMXdjZjV2Q1BzSnIKejBsMkJQNWhpSWNDUVN0RWVrdU94U005MzFROGt1ejFvS29SUkNSckhJK3EwUHJ1cjNWRG1HTDh2SklkaEJveQplZnBWNHZ2Tnc4bWhyd1R4cEdNM3BuZWc3WHo3aTdQTW1KZ0hnSXBQWkpERmRwZkNTNG05d2l4Y1BhTkN2akduCjl4Yko5d2RHRjJ3bTRMNUNMaE5wTHE4TENkdnJya3BCZjcrNWFvRmwrV1V2YWttZG94RmJuMWdYdldwQ2orNTkKNnhMcWJGczlFOGhVSHVLdEU5MnJYdGlIZ1NwdDNvbGxXbDBjZjBBdUVCaXFTK0Y4Rkk4Z1UyYkNXUnJ5ait1SwpmK3pzWW5JTmhwVnVwM01leFFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBYVl3RHdZRFZSMFRBUUgvCkJBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXRDRW5tT201aEZqWE1HYUp5d1gxa0FqZ2ttRXdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUJSS0NmM0NOU3RuZmdLeTZNaG1vbDF3TGtjY05zbTE5YUh6S2p3bTdiZ3hLWVJKVEpWVwpqTmJpQzY1YmRMMGt5a21LNzVxVm95cDdwU1k0Mk1lSjdQZ29HY2dQQURQVWJxWkhpZEQ3UVNzVlBTaXlmQTQ5Cng0Zzh5TFdleThpaitXK0pWVjB4cTRGa3pzeC9LTGhvcE9RdDd5Z2lzZnpSd1RGbkFWSkxFMWlIcFgraUdEQXUKWDNzSzJwUmxQY2lYMUQvd3RGRDdHek8xODk2TDk2TEs0YUV6NWpzeXpRbUp5K2ZGWnA1RktSZDhDTlhlTVlsNAp1UnFERWR0QkdlTC9VNW1TUU82ck5HengzUTF0aUYyRU1HN1dNQnlBd1lrYVBpYXYzbUZWRW4rbU51dEx6TVQwCkR1YmkyTXRPdE1SU0QxamRHM3ZNYmZLMGhiMEFYSUx5Z1dNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-93b5b3a.kyma.ondemand.com
contexts:
- name: shoot--kyma--c-93b5b3a
  context:
    cluster: shoot--kyma--c-93b5b3a
    user: shoot--kyma--c-93b5b3a
users:
- name: shoot--kyma--c-93b5b3a
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
