
---
apiVersion: v1
kind: Config
current-context: shoot--kyma--c-32f130e
clusters:
- name: shoot--kyma--c-32f130e
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lSQUxLb0JBeGMzaDRnUDdyWkpoZkpCRUV3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpNd01qRTVNVGN5TkRBd1doY05Nek13TWpFNU1UY3lOREF3V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS0lpCjFBSEIwZG9RNnNITDhUVERlQTR3NXJxL01XRlJ0RnF6akdJWkt1WHpoSm5ZalJMeUVZYmRjbnJYSXNSa2ZMcG0KTCs0ZmRUTkh6d2JmcmVYRVJ0SEVTODVyRUl6KzVYTkNXTy9QY0VLMXViVm9JQ0dXTWVXNE43VUNiODNTOGhxTQo3b1NkQk1VT21mc3loVXFJbEtTU2tZM3lhRWZxRWtFWWovbWtkYnVVN1ZFSFp3VmZSZElFdER3eGFudUdvR1ZVCmVLSDU3VlRtdmRxNUZhSS9INkdQL0VTM3JFa0J2dDQ5d2ZXY1R1bTdOUE1rdldPVk9FZzM3Si92OWlvRElZQmUKZ3lpanJYTTN0YlFMZkdLRTlzRG92R1djNFJDMFVxWWFELzFxNmFvQ1NiQmZaRWlBR3p2V3FpbjZaekZpUHZCOApnZFBqWFVVNHVuam5uYk1GOXdFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0dtTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKQWtwMTFiSXlCbzNSNXVaaWREVlNHd3NnWGhNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDZGtENEFvUTh6ekk4S09qWDBidHNuMjRwcENkNUdyakxJM0xGU2RiUTJoOG9Xd0dqZQpmVUlld0FpNURFQ3VKYkpXVXJiTnpQNmZEK0tNZ2R2UUxoaTRmdjIrTFdWeEdOaUJZdUp3aGdVNW9xeFhSQnpYCk5LU0ZjdmhJbGtPU0xWK1NvZzV0cWowQ0xxckNoNGZPNWx0UVZMYTE3aHN0eGRSbkt1RDc5L08rYnVaSDB5ZkkKUCtYYWM3Tnp1dXJIZDlhTURCWFNZbmlEVWVQMW5nUmJUS21PelBxZjI3UmVEc2RxUnJQeTQwNU5wblFIbjVwbApGZXh2aHBpSkhBYXdzU05KRDZ6Q0NkWlpMWXRHbGtQRUxlVm5qeFFSdXhkTEZTRDRkR0VYdTdvdVlBOE1MSFMwClVLZ2tpeTBRTjVYY2RwUHBWUHJTU1FzUm5XREZEN1djVzhKWgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-32f130e.kyma.ondemand.com
contexts:
- name: shoot--kyma--c-32f130e
  context:
    cluster: shoot--kyma--c-32f130e
    user: shoot--kyma--c-32f130e
users:
- name: shoot--kyma--c-32f130e
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
