
---
apiVersion: v1
kind: Config
current-context: shoot--kyma--f976b46
clusters:
- name: shoot--kyma--f976b46
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lSQU51VE4weW10QytCejYxc3ZBSDBKRFl3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpJeE1qQXhNakkwTnpVeVdoY05Nekl4TWpBeE1qSTBOelV5V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1pvCmtWS1JIQlBnMFFUNnVRdk9vKzBtN001WC90bEE3TjFFM1BEdFczaGZMcU9FYXluQ3Y3L3hxV2srWm9VQ29MaGcKazMvdmtOK0ZoSzNlU2c3QVFNaVlSOHd0VC80WFJMZ2pxZzdCK0taSHltZkluWXIwZDd3aENoazJGTDErQ0xteApHOE5FTWlOWld3KzBxOG84V1hoNzd3dWJyMkVCYUJsRC8yQTBGY0dkWjA2QlRIcjB6Z0hKbW1lL1FoYlJOR09SCkNoK1ZraWN1cXR4L1lZSHpsYkY3L1UxMGJiSnlzWjFBYU82amFsa0xZMHhZNm9aRHgvbm9UcENkVHFpb05hbGUKRHdJZUxuREZNTEJDZ0pXd0JNTGoxWHBzT2NHRUZBcFdxRmZJNjZDODZqdkIzRHZDb3NCV29ER3pPRXRHaXFyaQo2T2s2cm04QVljZ3o0MWlGYkJzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0dtTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGbzI5Ynk1bW1HL3MvK1R0UVFzczk2Um9TQVJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCZ2dmZkNxNU5vQzN2akZXanIxRCtZS3ltL3ZsVnNNMHJYR09VWTRlanExaUE4R0g0Tgo1a0t6M1BnYmloTFh1N2o5aWhBUlNCTVU2T2lLSlN1aXMwK1dBWnptYVY2RlZLUG5zSFd2ZHBmaGw4OEpZTlZxCnQzbGNsaXBGSGJwbjNBTk83VnJXNStlemladDZLdUNzejZ2SWt5eEVYVndMa245aEt2QUp5dENjWE9mSnlWajIKdU1xR1kyQnhiNGJJeTA3ck9LOWZXdnlybTZ1ckpMTzNiSjREVEhPZ1RvVjVnL0Rkbm1XZ2h2L3VQZ0UyQS9xZwpLQzBZSHNOcEVRYlFmL0l6aWNxbGlZUWh2SkNCNjdyRXErZENlVDZ3ditjaVdCMEtxKzZIcUZwSVJVQ3UvdzBTCnZoemp6N0U4dCtkVHJYMmVDNHlNL1JHTVpqczExS21XdE8xMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.f976b46.kyma.ondemand.com
contexts:
- name: shoot--kyma--f976b46
  context:
    cluster: shoot--kyma--f976b46
    user: shoot--kyma--f976b46
users:
- name: shoot--kyma--f976b46
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
