
---
apiVersion: v1
kind: Config
current-context: shoot--kyma--d5c6411
clusters:
- name: shoot--kyma--d5c6411
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWM2Z0F3SUJBZ0lRRENrNmJ5RHFWQTdTWTdLRnhEaURTVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TWpFeU1UY3hPRE00TWpsYUZ3MHpNakV5TVRjeE9ETTRNamxhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5TnczCjk1aXNIKzE1V24wVCtlOUgyeWEyWVBOSFllL2lOTFNtdzBxbTdOaUFhVW95MWU0Snp0VkxXcHcwWk5XSEtPNEQKdHUxS3V1eVYxeFFoV1ZYVXJCZ2UrUWtkZnRCZ0dNZW5UcWxQVVVSditjVVNQOXdpZDZQNjM0aUhHM0JDOWJ3NwppQzM0a3RCVzJESjlxRG1SbGdEaVlXdm5uWXNJUXR0b0o2c0plVDBIL0h2TzErMkYwWENJcDBrNU02MXN5MWpXCnV0ZGUrUGpuL0dVbDdWNnBkanUybGlBSmk3Z2svWFQyY0pzOGFweS80K3RtZmVWbUhkMGFyekFRU3dkOTZMVFkKeHIvTFJWNWNmUzE0YU9GalVUSFkxZ0JBMSszN2NrRkZTK2lUS2UzWDMzNk5jNWg5amNWZFBwOFhPSkd4N3dlTwpyRHllRTlEQzJuakl0NVROU1FJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBYVl3RHdZRFZSMFRBUUgvCkJBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXJkUE1LUHR3a080d1pHVnE5UHVyLzc4c1FKWXdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUZoeWd0SWd5aHNrd0VEb1U3RkNLeDZsN1FDVyszSEw0L1JydEZGNmxKV2U1UjJGTDM4RgpCNXZVSXR3SkhSS1A2VWMvVGkxRGo4UEJvSVF2V1dhR21QczJIVktqSVhROXlnZ3lraEg4ZkloSkNmUjRJMG5lCnhOZ2JOVUhlM2Y1c25pL2JFVURpWm1hN1ZTaGI5YllUWXVUcFRocEYzbXp3V2J1U0pIRXl0bFBINmxaZzRWTHIKYzFwQzNvZjFKK0ZITWYzc0pMZitOMDVWa1VOZktJeCtOWWpqSERBUFZib1FxUUI2MXAxVzR1eGszdW9JQ1pIcAp0UzBybHM2b1QxY21QWWkxSEpSMlFIcWVhcWtRNXJrMnE3RndWcmxVUC9QMjhueS9rQlVmMEp1Q0YrWU9zWnZiCmV1c2VPVXR0VjhNV2dwQnc5TTFpTUNJNDAzQmdscDlYSmxrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.d5c6411.kyma.ondemand.com
contexts:
- name: shoot--kyma--d5c6411
  context:
    cluster: shoot--kyma--d5c6411
    user: shoot--kyma--d5c6411
users:
- name: shoot--kyma--d5c6411
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
