kind: Deployment
apiVersion: apps/v1
# ----------------------
metadata:
    name: product
spec:
    replicas: 1
    selector:
        matchLabels:
            app: product
    template:
        metadata:
            labels: 
                app: product
        spec:
            containers:
                - name: product
                  image: mppise/product:1.1.0
                  ports:
                    - containerPort: 8080

---
kind: Service
apiVersion: v1
# -------------------
metadata:
    name: product-svc
spec:
    selector:
        app: product
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: online-store-product-apis
  labels:
    app.kubernetes.io/name: online-store-product-apis
spec:
  service:
    name: product-svc
    port: 8080
  host: productsapi.d5c6411.kyma.ondemand.com
  rules:
    - path: (/|$)(.*)
      methods:
        - GET
        - POST
        - DELETE
        - PUT
        - OPTIONS
      accessStrategies:
        - handler: allow
  gateway: kyma-gateway.kyma-system.svc.cluster.local
