apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: online-store
  labels:
    app.kubernetes.io/name: online-store
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods:
        - GET
      accessStrategies:
        - handler: allow
  host: online-store.f976b46.kyma.ondemand.com
  service:
    name: web-app-svc
    port: 80

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: online-store-order-apis
  labels:
    app.kubernetes.io/name: online-store-order-apis
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: (/|$)(.*)
      methods:
        - GET
        - POST
        - DELETE
        - PUT
        - OPTIONS
      accessStrategies:
        - handler: allow
  host: ordersapi.f976b46.kyma.ondemand.com
  service:
    name: order-svc
    port: 8080

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: online-store-product-apis
  labels:
    app.kubernetes.io/name: online-store-product-apis
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: (/|$)(.*)
      methods:
        - GET
        - POST
        - DELETE
        - PUT
        - OPTIONS
      accessStrategies:
        - handler: allow
  host: productsapi.f976b46.kyma.ondemand.com
  service:
    name: product-svc
    port: 8080
