kind: PersistentVolume
apiVersion: v1
# --------------------------
metadata:
  name: mongo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/mongo-pv"

---
kind: PersistentVolumeClaim
apiVersion: v1
# ---------------------------------
metadata:
  name: mongo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
