kind: Deployment
apiVersion: apps/v1
# -----------------------
metadata:
    name: mongo-express
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongo-express
    template:
        metadata:
            labels:
                app: mongo-express
        spec:
            containers:
                - name: mongo-express
                  image: mongo-express:latest
                  ports:
                    - containerPort: 8081
                  env:
                    - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                      valueFrom:
                        secretKeyRef:
                            name: secret
                            key: db_user
                    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: secret
                            key: db_password
                    - name: ME_CONFIG_MONGODB_SERVER
                      value: mongodb-svc

---

kind: Service
apiVersion: v1
# -----------------
metadata:
    name: mongo-express-svc
spec:
    type: LoadBalancer
    selector:
        app: mongo-express
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
