kind: Secret
apiVersion: v1
# -----------------
type: Opaque
metadata:
    name: github-secret
data:
    username: bXBwaXNlQGdtYWlsLmNvbQ==
    password: bnVxaHVoLTNaeXZreS1rZWh3aWM=

---
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world
spec:
  runtime: nodejs14
  source:
    gitRepository:
      url: "https://github.com/mppise/full-stack-microservices.git"
      baseDir: "/1.middleware/hello-world/"
      reference: "main"
      auth:
        type: "basic"
        secretName: "github-secret"

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world
spec:
  service:
    name: hello-world
    port: 80
  host: hello-world.f976b46.kyma.ondemand.com
  rules:
    - path: /.*
      methods:
        - GET
        - POST
        - DELETE
        - PUT
        - OPTIONS
      accessStrategies:
        - handler: allow
  gateway: kyma-gateway.kyma-system.svc.cluster.local
