kind: Secret
apiVersion: v1
# -----------------
type: Opaque
metadata:
    name: github-secret
data:
    usrername: bXBwaXNlQGdtYWlsLmNvbQ==
    password: bnVxaHVoLTNaeXZreS1rZWh3aWM=

---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
  name: hello-world
spec:
  url: "https://github.com/mppise/full-stack-microservices.git"
  auth:
    type: "basic"
    secretName: "github-secret"

---
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: hello-world
  name: hello-world
spec:
  type: git
  runtime: nodejs14
  source: hello-world
  reference: main
  baseDir: 1.middleware/hello-world/

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world
spec:
  service:
    name: hello-world
    port: 80
  host: hello-world.f976b46.kyma.ondemand.com
  rules:
    - path: /.*
      methods:
        - GET
        - POST
        - DELETE
        - PUT
        - OPTIONS
      accessStrategies:
        - handler: allow
  gateway: kyma-gateway.kyma-system.svc.cluster.local
