kind: Deployment
apiVersion: apps/v1
# ----------------------
metadata:
    name: order
spec:
    replicas: 1
    selector:
        matchLabels:
            app: order
    template:
        metadata:
            labels:
                app: order
        spec:
            containers:
                - name: order
                  image: mppise/order:1.1.0
                  ports:
                      - containerPort: 8080

---
kind: Service
apiVersion: v1
# -------------------
metadata:
    name: order-svc
spec:
    selector:
        app: order
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
