kind: Deployment
apiVersion: apps/v1
# ----------------------
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: mppise/order:1.1.0
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
# -------------------
metadata:
  name: order-svc
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: online-store-order-apis
  labels:
    app.kubernetes.io/name: online-store-order-apis
spec:
  service:
    name: order-svc
    port: 8080
  host: ordersapi.c-93b5b3a.kyma.ondemand.com
  rules:
    - path: (/|$)(.*)
      methods:
        - GET
        - POST
        - DELETE
        - PUT
        - OPTIONS
      accessStrategies:
        - handler: allow
  gateway: kyma-gateway.kyma-system.svc.cluster.local
